export const USER_LOGIN = 'USER_LOGIN'
export const SET_USER_INFO = 'SET_USER_INFO'
export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'
export const SET_SESSION = 'SET_SESSION'
export const ADD_OVERAGE = 'ADD_OVERAGE'
export const LOTTERY = 'LOTTERY'